services:
  - type: web
    name: django-blog
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myblog.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0